// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"Patito/token"
)

const (
	NoState    = -1
	NumStates  = 81
	NumSymbols = 109
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '_'
1: '_'
2: '0'
3: '.'
4: '"'
5: '"'
6: 'p'
7: 'r'
8: 'o'
9: 'g'
10: 'r'
11: 'a'
12: 'm'
13: ';'
14: 'm'
15: 'a'
16: 'i'
17: 'n'
18: 'e'
19: 'n'
20: 'd'
21: 'v'
22: 'a'
23: 'r'
24: ':'
25: ','
26: 'i'
27: 'n'
28: 't'
29: 'f'
30: 'l'
31: 'o'
32: 'a'
33: 't'
34: 'v'
35: 'o'
36: 'i'
37: 'd'
38: '('
39: ')'
40: '['
41: ']'
42: '{'
43: '}'
44: 'p'
45: 'r'
46: 'i'
47: 'n'
48: 't'
49: '='
50: 'w'
51: 'h'
52: 'i'
53: 'l'
54: 'e'
55: 'd'
56: 'o'
57: 'i'
58: 'f'
59: 'e'
60: 'l'
61: 's'
62: 'e'
63: 'r'
64: 'e'
65: 't'
66: 'u'
67: 'r'
68: 'n'
69: '>'
70: '<'
71: '!'
72: '='
73: '='
74: '='
75: '+'
76: '-'
77: '*'
78: '/'
79: ' '
80: '\t'
81: '\n'
82: '\r'
83: '/'
84: '/'
85: '\t'
86: '\n'
87: '\r'
88: '/'
89: '*'
90: '\t'
91: '\n'
92: '\r'
93: '*'
94: '/'
95: 'a'-'z'
96: 'A'-'Z'
97: 'a'-'z'
98: 'A'-'Z'
99: '0'-'9'
100: '1'-'9'
101: '0'-'9'
102: '0'-'9'
103: '0'-'9'
104: ' '-'!'
105: '#'-'~'
106: ' '-'~'
107: ' '-'~'
108: .
*/
