// Code generated by gocc; DO NOT EDIT.

package parser

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : "program" id ";" P_VAR P_FUNCS "main" BODY "end"	<<  >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P_VAR : VARS	<<  >>`,
		Id:         "P_VAR",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P_VAR : empty	<<  >>`,
		Id:         "P_VAR",
		NTType:     2,
		Index:      3,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `VARS : "var" FVAR_LIST	<<  >>`,
		Id:         "VARS",
		NTType:     3,
		Index:      4,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FVAR_LIST : F_VAR FVAR_LIST	<<  >>`,
		Id:         "FVAR_LIST",
		NTType:     4,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FVAR_LIST : empty	<<  >>`,
		Id:         "FVAR_LIST",
		NTType:     4,
		Index:      6,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `F_VAR : id R_ID ":" TYPE ";"	<<  >>`,
		Id:         "F_VAR",
		NTType:     5,
		Index:      7,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_ID : "," id R_ID	<<  >>`,
		Id:         "R_ID",
		NTType:     6,
		Index:      8,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_ID : empty	<<  >>`,
		Id:         "R_ID",
		NTType:     6,
		Index:      9,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `TYPE : "int"	<<  >>`,
		Id:         "TYPE",
		NTType:     7,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TYPE : "float"	<<  >>`,
		Id:         "TYPE",
		NTType:     7,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P_FUNCS : empty	<<  >>`,
		Id:         "P_FUNCS",
		NTType:     8,
		Index:      12,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `P_FUNCS : FUNCS P_FUNCS	<<  >>`,
		Id:         "P_FUNCS",
		NTType:     8,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_T : TYPE	<<  >>`,
		Id:         "F_T",
		NTType:     9,
		Index:      14,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_T : "void"	<<  >>`,
		Id:         "F_T",
		NTType:     9,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FUNCS : F_T id "(" S_T ")" FUNC_LOCALS BODY ";"	<<  >>`,
		Id:         "FUNCS",
		NTType:     10,
		Index:      16,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FUNC_LOCALS : "[" S_V "]"	<<  >>`,
		Id:         "FUNC_LOCALS",
		NTType:     11,
		Index:      17,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FUNC_LOCALS : empty	<<  >>`,
		Id:         "FUNC_LOCALS",
		NTType:     11,
		Index:      18,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `S_T : I_T R_T	<<  >>`,
		Id:         "S_T",
		NTType:     12,
		Index:      19,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_T : empty	<<  >>`,
		Id:         "S_T",
		NTType:     12,
		Index:      20,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `R_T : "," I_T R_T	<<  >>`,
		Id:         "R_T",
		NTType:     13,
		Index:      21,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_T : empty	<<  >>`,
		Id:         "R_T",
		NTType:     13,
		Index:      22,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `S_V : VARS	<<  >>`,
		Id:         "S_V",
		NTType:     14,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_V : empty	<<  >>`,
		Id:         "S_V",
		NTType:     14,
		Index:      24,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `I_T : id ":" TYPE	<<  >>`,
		Id:         "I_T",
		NTType:     15,
		Index:      25,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `BODY : "{" P_STAT "}"	<<  >>`,
		Id:         "BODY",
		NTType:     16,
		Index:      26,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P_STAT : STATEMENT P_STAT	<<  >>`,
		Id:         "P_STAT",
		NTType:     17,
		Index:      27,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P_STAT : empty	<<  >>`,
		Id:         "P_STAT",
		NTType:     17,
		Index:      28,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : ASSIGN	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : CONDITION	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      30,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : CYCLE	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : F_CALL ";"	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      32,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : PRINT	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `STATEMENT : "[" P_STAT "]"	<<  >>`,
		Id:         "STATEMENT",
		NTType:     18,
		Index:      34,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PRINT : "print" "(" PRINT_P ")" ";"	<<  >>`,
		Id:         "PRINT",
		NTType:     19,
		Index:      35,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PRINT_P : E_PRINT R_PRINT	<<  >>`,
		Id:         "PRINT_P",
		NTType:     20,
		Index:      36,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `E_PRINT : EXPRESSION	<<  >>`,
		Id:         "E_PRINT",
		NTType:     21,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `E_PRINT : cte_string	<<  >>`,
		Id:         "E_PRINT",
		NTType:     21,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_PRINT : "," PRINT_P	<<  >>`,
		Id:         "R_PRINT",
		NTType:     22,
		Index:      39,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_PRINT : empty	<<  >>`,
		Id:         "R_PRINT",
		NTType:     22,
		Index:      40,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ASSIGN : id "=" EXPRESSION ";"	<<  >>`,
		Id:         "ASSIGN",
		NTType:     23,
		Index:      41,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CYCLE : "while" "(" EXPRESSION ")" "do" BODY ";"	<<  >>`,
		Id:         "CYCLE",
		NTType:     24,
		Index:      42,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CONDITION : "if" "(" EXPRESSION ")" BODY ";"	<<  >>`,
		Id:         "CONDITION",
		NTType:     25,
		Index:      43,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CONDITION : "if" "(" EXPRESSION ")" BODY "else" BODY ";"	<<  >>`,
		Id:         "CONDITION",
		NTType:     25,
		Index:      44,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXPRESSION : EXP REL_TAIL	<<  >>`,
		Id:         "EXPRESSION",
		NTType:     26,
		Index:      45,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL_TAIL : REL_OP EXP	<<  >>`,
		Id:         "REL_TAIL",
		NTType:     27,
		Index:      46,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL_TAIL : empty	<<  >>`,
		Id:         "REL_TAIL",
		NTType:     27,
		Index:      47,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `REL_OP : ">"	<<  >>`,
		Id:         "REL_OP",
		NTType:     28,
		Index:      48,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL_OP : "<"	<<  >>`,
		Id:         "REL_OP",
		NTType:     28,
		Index:      49,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL_OP : "!="	<<  >>`,
		Id:         "REL_OP",
		NTType:     28,
		Index:      50,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL_OP : "=="	<<  >>`,
		Id:         "REL_OP",
		NTType:     28,
		Index:      51,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP : TERMINO EXP_P	<<  >>`,
		Id:         "EXP",
		NTType:     29,
		Index:      52,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP_P : "+" TERMINO EXP_P	<<  >>`,
		Id:         "EXP_P",
		NTType:     30,
		Index:      53,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP_P : "-" TERMINO EXP_P	<<  >>`,
		Id:         "EXP_P",
		NTType:     30,
		Index:      54,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP_P : empty	<<  >>`,
		Id:         "EXP_P",
		NTType:     30,
		Index:      55,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `TERMINO : FACTOR TERMINO_P	<<  >>`,
		Id:         "TERMINO",
		NTType:     31,
		Index:      56,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERMINO_P : "*" FACTOR TERMINO_P	<<  >>`,
		Id:         "TERMINO_P",
		NTType:     32,
		Index:      57,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERMINO_P : "/" FACTOR TERMINO_P	<<  >>`,
		Id:         "TERMINO_P",
		NTType:     32,
		Index:      58,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERMINO_P : empty	<<  >>`,
		Id:         "TERMINO_P",
		NTType:     32,
		Index:      59,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `FACTOR : S_OP FACTOR_CORE	<<  >>`,
		Id:         "FACTOR",
		NTType:     33,
		Index:      60,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FACTOR_CORE : "(" EXPRESSION ")"	<<  >>`,
		Id:         "FACTOR_CORE",
		NTType:     34,
		Index:      61,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FACTOR_CORE : id FACTOR_SUFFIX	<<  >>`,
		Id:         "FACTOR_CORE",
		NTType:     34,
		Index:      62,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FACTOR_CORE : CTE	<<  >>`,
		Id:         "FACTOR_CORE",
		NTType:     34,
		Index:      63,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FACTOR_SUFFIX : "(" S_E ")"	<<  >>`,
		Id:         "FACTOR_SUFFIX",
		NTType:     35,
		Index:      64,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FACTOR_SUFFIX : empty	<<  >>`,
		Id:         "FACTOR_SUFFIX",
		NTType:     35,
		Index:      65,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `S_OP : "+"	<<  >>`,
		Id:         "S_OP",
		NTType:     36,
		Index:      66,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_OP : "-"	<<  >>`,
		Id:         "S_OP",
		NTType:     36,
		Index:      67,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_OP : empty	<<  >>`,
		Id:         "S_OP",
		NTType:     36,
		Index:      68,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `CTE : cte_int	<<  >>`,
		Id:         "CTE",
		NTType:     37,
		Index:      69,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CTE : cte_float	<<  >>`,
		Id:         "CTE",
		NTType:     37,
		Index:      70,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_CALL : id "(" S_E ")"	<<  >>`,
		Id:         "F_CALL",
		NTType:     38,
		Index:      71,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_E : EXPRESSION R_E	<<  >>`,
		Id:         "S_E",
		NTType:     39,
		Index:      72,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_E : empty	<<  >>`,
		Id:         "S_E",
		NTType:     39,
		Index:      73,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `R_E : "," EXPRESSION R_E	<<  >>`,
		Id:         "R_E",
		NTType:     40,
		Index:      74,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `R_E : empty	<<  >>`,
		Id:         "R_E",
		NTType:     40,
		Index:      75,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
}
